<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<BuiltInComInteropSupport>true</BuiltInComInteropSupport>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<ApplicationIcon>lol-icon.ico</ApplicationIcon>
		<DebugType>embedded</DebugType>
	</PropertyGroup>
	<ItemGroup>
		<Content Include="lol-icon.ico" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Avalonia.Desktop" Version="$(AvaloniaVersion)" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\LolStealthMode\LolStealthMode.csproj" />
	</ItemGroup>
</Project>
